GET http://localhost:5000/users

###
GET http://localhost:5000/users/8

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Supri2",
    "email": "supri@gmail.com",
    "gender": "Laki"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "SupriYONO",
    "email": "supri@gmail.com",
    "gender": "Laki"
}


###
DELETE http://localhost:5000/users/4
